# Generated by Django 5.0.3 on 2024-03-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='escolauser',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='escolauser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='escolauser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
        migrations.DeleteModel(
            name='EscolaUser',
        ),
    ]
