# Generated by Django 5.0.3 on 2024-03-31 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0005_escola_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('orgao_emissor', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
                ('pai', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appMatricula.endereco')),
            ],
        ),
    ]
