# Generated by Django 5.0.3 on 2024-03-31 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0006_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMatricula.escola'),
        ),
    ]
