# Generated by Django 5.0.3 on 2024-03-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0007_aluno_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMatricula.escola'),
        ),
    ]
