# Generated by Django 5.0.3 on 2024-04-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0008_alter_aluno_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
