# Generated by Django 5.0.3 on 2024-04-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0010_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMatricula.endereco'),
        ),
    ]
