# Generated by Django 5.0.3 on 2024-04-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0014_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
