# Generated by Django 5.0.3 on 2024-04-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0017_customuser_alter_escola_userescola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
