# Generated by Django 5.0.3 on 2024-04-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0018_alter_escola_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMatricula.endereco'),
        ),
    ]
