# Generated by Django 5.0.3 on 2024-04-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0027_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aniversario',
            field=models.DateTimeField(null=True),
        ),
    ]
