# Generated by Django 5.0.3 on 2024-04-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0029_alter_aluno_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aniversario',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
