# Generated by Django 5.0.3 on 2024-05-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMatricula', '0034_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='telefone',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
